# Generated by Django 3.2.4 on 2021-06-05 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Rather Not Say')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'ordering': ('start', 'end'),
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('index', models.IntegerField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stop_problem.sequence')),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('index', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='SequenceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_answers', to='stop_problem.player')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_answers', to='stop_problem.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField()),
                ('sequence_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stop_problem.sequenceanswer')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stop_problem.timeperiod')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stop_problem.value')),
            ],
        ),
    ]
