# Generated by Django 3.2.4 on 2021-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_problem', '0002_auto_20210606_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='sequenceanswer',
            name='is_accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
