# Generated by Django 3.2.4 on 2021-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_problem', '0003_auto_20210606_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceanswer',
            name='chosen_index',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
